---
title: "Homework 4"
subtitle: "STAT5514: Regression Analysis"
author: "Alexander Durbin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE)
```

```{r, include = FALSE}

library(tidyverse)
library(MASS)
library(broom)

```

```{r}

raw <- read.table('data.txt', header = TRUE)
y <- raw$Lab
x <- raw$Field

f1 <- lm(y ~ x)
bo <- coefficients(f1)
r2 <- residuals(f1)^2
f2 <- glm(r2 ~ x, family = Gamma(link = 'log'), maxit = 1000)
w = rep(0, nrow(raw))
w <- sapply(x, function(g) return(1 / exp(coefficients(f1)[1] + coefficients(f1)[2] * g)))
y <- sqrt(w) * y
x <- sqrt(w) * x
bn <- coefficients(lm(y ~ x))

while(all(abs(bn - bo) > 1E-5)){
  
  f1 <- lm(y ~ x)
  r2 <- residuals(f1)^2
  f2 <- glm(r2 ~ x, family = Gamma(link = 'log'), maxit = 1000)
  w = rep(0, nrow(raw))
  w <- sapply(x, function(g) return(1 / exp(coefficients(f1)[1] + coefficients(f1)[2] * g)))
  y <- sqrt(w) * y
  x <- sqrt(w) * x
  bo <- coefficients(f1)
  bn <- coefficients(lm(y ~ x))
  
}

```

```{r}

cat("The simple linear regression coefficients are:\nIntercept: ", coefficients(lm(Lab ~ Field, data = raw))[1],"\nSlope: ", coefficients(lm(Lab ~ Field, data = raw))[2])

cat("The robust linear regression coefficients are:\nIntercept: ", coefficients(rlm(Lab ~ Field, data = raw))[1],"\nSlope: ", coefficients(rlm(Lab ~ Field, data = raw))[2])

cat("The dual regression coefficients are:\nIntercept: ", bn[1],"\nSlope: ", bn[2])

```

```{r}

mod <- lm(Lab ~ Field, data = raw)
df <- augment(mod)
ggplot(data = df) + 
  geom_jitter(mapping = aes(x = .fitted, y = .resid)) +
  ggtitle("Residuals Versus Fitted")

```

```{r}

ggplot(data = raw) +
  stat_qq(mapping = aes(sample = Lab)) +
  ggtitle("Normal QQ Plot")

```

```{r}
ggplot(data = raw) +
  geom_jitter(mapping = aes(x = Field, y = Lab)) +
  geom_smooth(mapping = aes(x = Field, y = Lab, color = 'lm'), method = 'lm', se = FALSE, fullrange = TRUE) +
  geom_smooth(mapping = aes(x = Field, y = Lab, color = 'rlm'), method = 'rlm', se = FALSE, fullrange = TRUE) +
  geom_abline(mapping = aes(color = 'dual', slope = bn[2], intercept = bn[1])) +
  scale_color_manual(values = c('red', 'blue', 'orange')) +
  ggtitle("Regression Fits")
```
